vim.api.nvim_set_hl(0, "NeoTreeTabInactive", { bg = "#21252b" })
vim.api.nvim_set_hl(0, "NeoTreeTabSeparatorInactive", { bg = "#21252b" })
vim.api.nvim_set_hl(0, "NeoTreeDirectoryIcon", { fg = "#61afef" })
vim.api.nvim_set_hl(0, "NeoTreeExpander", { fg = "#c5c5c5" })
vim.api.nvim_set_hl(0, "DashboardHeader", { fg = "#5777c6" })
vim.api.nvim_set_hl(0, "SmoothCursor", { fg = "#e5c07b" })
