require "plugins.configs.neoscroll-nvim"
require "plugins.configs.lsp-config"
require "plugins.configs.diagnostic"
require "plugins.configs.auto-completion"
require "plugins.configs.help-window-config"
require "plugins.configs.neotree-nvim" 
require "plugins.configs.lualine-nvim"
-- require "plugins.configs.barbar-nvim"
require "plugins.configs.mason-nvim"
require "plugins.configs.toggleterm-nvim"
