local home = os.getenv("HOME")
local lspconfig = require("lspconfig")
--
-- -- File types that signify a Java project's root directory. This will be
-- -- used by eclipse to determine what constitutes a workspace
-- local root_markers = { "gradlew", "mvnw", ".git" }
--
-- lspconfig.clangd.setup {
--   root_dir = lspconfig.util.root_pattern('gradlew', 'mvnw', '.git')
-- }
--
-- lspconfig.jdtls.start_or_attach({
--   cmd = {
--     'java',
-- '-Declipse.application=org.eclipse.jdt.ls.core.id1',
--     '-Dosgi.bundles.defaultStartLevel=4',
--     '-Declipse.product=org.eclipse.jdt.ls.core.product',
--     '-Dlog.protocol=true',
--     '-Dlog.level=ALL',
--     '-Xmx1g',
--     '--add-modules=ALL-SYSTEM',
--     '--add-opens', 'java.base/java.util=ALL-UNNAMED',
--     '--add-opens', 'java.base/java.lang=ALL-UNNAMED',
--   }
-- })
